Cir-697 publishing process
ONSdigital/cir-runbooks pull request #4
Opened 2024-04-24 14:13 UTC by Mohammed1804

PR for https://jira.ons.gov.uk/browse/SDSS-697?workflowName=SDSS%3A+Project+Management+Workflow&stepId=2

Please read the read me to test. 
At the moment there is no description field in the CIR schema definitions (this is a mandatory key) so posting this will not work. Instead I have included a test_schema.json file which should work when posted 

Description field present in runbook so historic CIs without the description field won't work (expected behaviour). Leaving description field in the runbook as there is a need to populate this moving forward.
Author likely to add a 'generic' placeholder to the description field to historic CIs they already hold when performing the bulk migration to the CIR. However, this may change pending discussions with the Business as there may be a need for these to be migrated with a description that 'makes sense.'

2024-04-29 11:39 UTC, IsaiahLai111 requested changes

2024-04-29 11:39 UTC, IsaiahLai111 commented on collection-instrument-create/CIR_test_schema_cleaned/test_schema.json
This schema is for testing and should not be a part of the runbook, as well as its folder

2024-04-29 11:39 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +    return total_errors_found
You should rearrange this block so that all the error handlings are done ahead of the normal code block

2024-04-29 11:39 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +                )
Validation should be done before calling the endpoint, if it is needed.

2024-04-29 11:39 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +                    f"Additional Fields Found {additional_keys}\n\n\n"
Good. It is a nice thing to have the unexpected fields expose here.
However, this should be done as a part of validation before calling the endpoint, and block the CI publish if they are found.
This is because since any unexpected fields within a CI will not be processed into CIR, we should avoid data inconsistency among the data in FireStore and the CI published.

2024-04-29 11:39 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +                log_file.write(f"CI file name {file_name}\n" f"CI response {ci_response_json}\n\n")
This line is being repeated in line 252. Extract and rearrange it so that it won't have to be repeated.

2024-04-29 11:39 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +                    f"Optional Missing Fields {optional_missing_keys}\n"
If they are optional fields, then they could not be missing fields

2024-04-29 11:39 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +            log_file.write(f"Error: Required key(s) not found in the response JSON for CI file: {file_name}\n\n")
I am not sure which line will be triggering this exception.

2024-04-29 11:39 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +        )
Good. It is always a nice thing to have a summary of the process.

2024-04-29 11:39 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +        exit(1)  # Exit the script if authentication fails
Copy to logic in sds runbook to ensure consistency in authentication

2024-04-29 11:39 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +    sds_manager.cleanup_key_file(key_filename, key_id, project_id)
Key deletion should not be part of this function. Since you create the key in the main script, you should delete it in the main script as well

2024-04-29 11:39 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +    process_ci_files(ci_list, json_files, audience, key_filename, key_id, details["project_id"])
Copy the structure from sds runbook to make sure generated key will be deleted even if error is encountered in the middle of the process

2024-04-30 18:16 UTC, Mohammed1804 commented on collection-instrument-create/publish_ci.py
> +            log_file.write(f"Error: Required key(s) not found in the response JSON for CI file: {file_name}\n\n")
This line attempts to access the key "status" in the ci_response_json dictionary. If the key "status" is not present in the dictionary, a KeyError will be raised, triggering the except KeyError block

2024-05-01 11:21 UTC, IsaiahLai111 requested changes

2024-05-01 11:21 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +                    )
As per spoken, it is better to rearrange this validation block before processing the CI, and remove the validation for optional missing keys

2024-05-01 11:21 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +        cir_manager.cleanup_key_file(key_filename, key_id, project_id)
You won't need these two lines as the key deletion part is at the main script now

2024-05-01 11:21 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +        cir_manager.cleanup_key_file(key_filename, key_id, project_id)
You need a try block here to handle the key cleanup at the "finally" block to ensure that it will be processed even when error occurs. Just reference to the structure in sds-runbook

2024-05-08 10:17 UTC, JacobHarrisonONS commented on collection-instrument-create/publish_ci.py
> +import glob
this isnt used, don't forget to lint.

2024-05-08 12:00 UTC, IsaiahLai111 requested changes

2024-05-08 12:00 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +                f"CI response {ci_response_json}\n\n"
This validation blocks should be run as soon as the ci is loaded from file, before the ci is published to the endpoint.

2024-05-08 12:00 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +                f"CI response {ci_response_json}\n\n"
Do you wish to print these lines or write them to log file?

2024-05-08 12:00 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +                        ci = CIProcessor.load_ci_from_file(file_path)
Good! It is better than loading all the CI into a list

2024-05-08 12:00 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +        cir_manager.cleanup_key_file(key_filename, key_id, project_id)
You should delete these two lines as you have key file cleanup in the main script

2024-05-08 12:00 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +        cir_manager.cleanup_key_file(key_filename, key_id, project_id)
You will need a try block here to ensure the key file cleanup will still process in case of any uncatched exception

2024-05-08 12:00 UTC, IsaiahLai111 commented on README.md
> +- Enter the absolute path of the folder where you stored the CI JSON files.
Can you provide a sample of an absolute path so that the user can be more aware that the relative path will not work?

2024-05-08 12:56 UTC, JacobHarrisonONS commented on collection-instrument-create/publish_ci.py
> +                    raise Exception("Key ID not found in the key file.")
could you throw a more specific exception rather than Exception ?

2024-05-08 13:00 UTC, JacobHarrisonONS commented on collection-instrument-create/publish_ci.py
> +        directory_path, audience, key_filename, key_id, project_id, base_url
double check all your params are being used

2024-05-08 14:29 UTC, JacobHarrisonONS commented on collection-instrument-create/publish_ci.py
> +    def main():
should this have the parameter self

2024-05-08 15:06 UTC, Mohammed1804 commented on collection-instrument-create/publish_ci.py
> +    def main():
self parameter is mainly used in methods of classes to refer to the instance of the class itself. so for standalone functions like main(), which are not part of a class, self is not used as a parameter

2024-05-09 12:11 UTC, IsaiahLai111 requested changes

2024-05-09 12:11 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +
You have already called this function in `process_ci_files` and no longer to call it here

2024-05-09 12:11 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +                )
This is duplicated

2024-05-09 12:11 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +            return total_errors_found
total_errors_found should be incremented by 1 in this case before returning

2024-05-09 12:11 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +class CIRvalidation:
Consider rename this class to CIValidator for consistency

2024-05-09 13:18 UTC, Mohammed1804 commented on collection-instrument-create/publish_ci.py
> +        directory_path, audience, key_filename, key_id, project_id, base_url
All parameters are required.

2024-05-09 14:31 UTC, IsaiahLai111 requested changes

2024-05-09 14:31 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +    def validate_ci_keys(ci):
missing the `log_file` in parameter

2024-05-09 14:31 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +            logging.error(log_message)
write the message to the `log_file`

2024-05-09 14:31 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +                        logging.error(f"Error loading CI file {file_path}: {e}")
Increment total errors

2024-05-09 14:31 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +                f"Total Number of Json files to be published: {len(os.listdir(directory_path))}\n"
Change to use `total_json_files`

2024-05-09 14:31 UTC, IsaiahLai111 commented on collection-instrument-create/publish_ci.py
> +            return total_errors_found
This return value is not used

2024-05-09 15:17 UTC, IsaiahLai111 approved these changes

2024-05-10 13:03 UTC, JacobHarrisonONS commented on collection-instrument-create/publish_ci.py
> +                raise Exception("Key ID extraction failed.")
raising generic exception rather than a specfic one

2024-05-10 13:08 UTC, JacobHarrisonONS commented on collection-instrument-create/publish_ci.py
> +        directory_path, audience, key_filename, key_id, project_id, base_url, log_file
unused params in function. looks like key_filename, key_id, project_id and log_file are unused are these required? they are also being passed in at the function call if you change this.

2024-05-10 13:12 UTC, JacobHarrisonONS commented on collection-instrument-create/publish_ci.py
> +            cir_manager.cleanup_key_file(key_filename, key_id, project_id)
i get a warning for cir_manager, key_filename and key_id being refrenced before assignment, i assume this is cause of the try catch

2024-05-13 08:33 UTC, Mohammed1804 commented on collection-instrument-create/publish_ci.py
> +            cir_manager.cleanup_key_file(key_filename, key_id, project_id)
Yes, that is correct

2024-05-16 12:21 UTC, JacobHarrisonONS commented on Makefile
> +	python -m mypy . --exclude env --disable-error-code attr-defined --disable-error-code import
we dont use mypy anymore, i have recently removed this from CIR.

2024-05-17 11:59 UTC, IsaiahLai111 approved these changes

2024-05-20 10:38 UTC, JacobHarrisonONS approved these changes

2024-06-04 09:33 UTC, merged